name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Zip Lambda functions
        run: |
          mkdir -p SecurePaste/terraform/artifacts
          zip -j SecurePaste/terraform/artifacts/create.zip SecurePaste/app/lambda/create/lambda_function.py
          zip -j SecurePaste/terraform/artifacts/get.zip SecurePaste/app/lambda/get/lambda_function.py
          unzip -l SecurePaste/terraform/artifacts/create.zip
          unzip -l SecurePaste/terraform/artifacts/get.zip

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: SecurePaste/terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
