name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Infra with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terra-devsec-aws/SecurePaste/terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python for Lambda packaging
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Zip Lambda functions
        run: |
          mkdir -p $GITHUB_WORKSPACE/SecurePaste/terraform/artifacts
          zip -j $GITHUB_WORKSPACE/SecurePaste/terraform/artifacts/create.zip \
            $GITHUB_WORKSPACE/SecurePaste/app/lambda/create/lambda_function.py
          zip -j $GITHUB_WORKSPACE/SecurePaste/terraform/artifacts/get.zip \
            $GITHUB_WORKSPACE/SecurePaste/app/lambda/get/lambda_function.py
          unzip -l $GITHUB_WORKSPACE/SecurePaste/terraform/artifacts/create.zip
          unzip -l $GITHUB_WORKSPACE/SecurePaste/terraform/artifacts/get.zip

      - name: Terraform Init
        run: terraform init
        working-directory: $GITHUB_WORKSPACE/SecurePaste/terraform
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
